# Generated by Django 2.2.5 on 2019-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190927_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
