# Generated by Django 2.2.5 on 2019-10-04 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191004_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='present',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
