# Generated by Django 2.2.5 on 2019-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191004_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
