# Generated by Django 2.2.5 on 2019-10-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE')], default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
