# Generated by Django 2.2.5 on 2019-10-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
