# Generated by Django 2.2.5 on 2019-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fees_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='no',
            field=models.CharField(default=None, max_length=5, unique=True),
        ),
    ]
