# Generated by Django 2.2.5 on 2019-11-04 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_newregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='amount',
            field=models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(9000), django.core.validators.MaxValueValidator(15000)]),
            preserve_default=False,
        ),
    ]
